# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  environment.systemPackages = with pkgs; [ nfs-utils ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.supportedFilesystems = [ "nfs" ];
  boot.kernelModules = [ "kvm-intel" "v4l2loopback" "nfs" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback ];
  boot.kernelParams = ["mitigations=off"];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3cf44fcd-8ae8-435c-9141-3a5e94274acc";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8E44-0380";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/ssd" =
    { device = "/dev/disk/by-uuid/0078EAAF78EAA2A0";
      fsType = "ntfs";
    };

  fileSystems."/mnt/ssd2" =
    { device = "/dev/disk/by-uuid/94c448e9-5789-46b7-b956-bb7c0d96c299";
      fsType = "btrfs";
    };

  fileSystems."/mnt/nfs" = 
  {
   device = "192.168.254.113:/mnt/media";
   fsType = "nfs";
   options = [
      "x-gvfx-show"
   ];
  };

  fileSystems."/mnt/nfs2" = 
  {
   device = "192.168.254.113:/mnt/media2";
   fsType = "nfs";
   options = [
      "x-gvfx-show"
   ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
